import type { CivilLawCurriculumMapping } from "@/lib/appraisal-first/types";

export const CIVIL_LAW_CURRICULUM_MAPPINGS: CivilLawCurriculumMapping[] = [
  {
    questionId: "civil_law-1",
    primaryNodeId: "civil_law.agency.authority",
    linkedNodeIds: ["civil_law.agency.apparent_authority"],
    chapterId: "general_provisions",
    chapterName: "민법총칙",
    topicId: "agency",
    topicName: "대리",
    subtopicId: "authority",
    subtopicName: "대리권",
    correctChoiceId: "2",
    expectedSeconds: 80,
    difficulty: "medium",
    examWeight: 4,
    reviewWeight: 4,
    coachingWeight: 4,
    testedConceptType: "rule",
    requiresArticleMemory: true,
    requiresCaseLogic: false,
    requiresComparison: true,
    mappingConfidence: "high",
    defaultRootCauseTags: ["condition_missing", "article_requirement_gap"],
  },
  {
    questionId: "civil_law-2",
    primaryNodeId: "civil_law.intent.mistake",
    linkedNodeIds: ["civil_law.intent.fraud_duress"],
    chapterId: "general_provisions",
    chapterName: "민법총칙",
    topicId: "declaration_of_intent",
    topicName: "의사표시",
    subtopicId: "mistake",
    subtopicName: "착오",
    correctChoiceId: "4",
    expectedSeconds: 95,
    difficulty: "high",
    examWeight: 5,
    reviewWeight: 5,
    coachingWeight: 5,
    testedConceptType: "comparison",
    requiresArticleMemory: true,
    requiresCaseLogic: true,
    requiresComparison: true,
    mappingConfidence: "high",
    defaultRootCauseTags: ["mistake_fraud_confusion", "choice_comparison_failure"],
  },
  {
    questionId: "civil_law-3",
    primaryNodeId: "civil_law.invalidity.cancellation",
    linkedNodeIds: ["civil_law.invalidity.void"],
    chapterId: "general_provisions",
    chapterName: "민법총칙",
    topicId: "invalidity_cancellation",
    topicName: "무효와 취소",
    subtopicId: "cancellation",
    subtopicName: "취소",
    correctChoiceId: "1",
    expectedSeconds: 80,
    difficulty: "medium",
    examWeight: 4,
    reviewWeight: 4,
    coachingWeight: 4,
    testedConceptType: "comparison",
    requiresArticleMemory: true,
    requiresCaseLogic: false,
    requiresComparison: true,
    mappingConfidence: "high",
    defaultRootCauseTags: ["void_cancel_confusion", "legal_effect_unclear"],
  },
  {
    questionId: "civil_law-4",
    primaryNodeId: "civil_law.property.registration",
    linkedNodeIds: ["civil_law.property.change_by_juristic_act"],
    chapterId: "property_law",
    chapterName: "물권법",
    topicId: "real_right_change",
    topicName: "물권변동",
    subtopicId: "registration",
    subtopicName: "등기",
    correctChoiceId: "2",
    expectedSeconds: 85,
    difficulty: "medium",
    examWeight: 5,
    reviewWeight: 5,
    coachingWeight: 5,
    testedConceptType: "exception",
    requiresArticleMemory: true,
    requiresCaseLogic: true,
    requiresComparison: false,
    mappingConfidence: "high",
    defaultRootCauseTags: ["exception_clause_missed", "scope_limit_missed"],
  },
  {
    questionId: "civil_law-5",
    primaryNodeId: "civil_law.security.lien",
    linkedNodeIds: ["civil_law.security.mortgage"],
    chapterId: "property_law",
    chapterName: "물권법",
    topicId: "security_right",
    topicName: "담보물권",
    subtopicId: "lien",
    subtopicName: "유치권",
    correctChoiceId: "3",
    expectedSeconds: 95,
    difficulty: "high",
    examWeight: 5,
    reviewWeight: 5,
    coachingWeight: 5,
    testedConceptType: "case_application",
    requiresArticleMemory: true,
    requiresCaseLogic: true,
    requiresComparison: true,
    mappingConfidence: "high",
    defaultRootCauseTags: ["fact_pattern_mapping_error", "condition_combination_failure"],
  },
];

export function getCivilLawCurriculumMapping(questionId: string) {
  return CIVIL_LAW_CURRICULUM_MAPPINGS.find((mapping) => mapping.questionId === questionId);
}
