import type { RootCauseTagDefinition, RootCauseTagId } from "@/lib/appraisal-first/types";

export const CIVIL_LAW_ROOT_CAUSE_TAGS: RootCauseTagDefinition[] = [
  {
    tagId: "definition_unclear",
    group: "concept_gap",
    internalName: "Definition unclear",
    userLabel: "개념 정의 불안정",
    summaryLabel: "개념 공백",
    reviewPriorityWeight: 45,
    reviewAction: "핵심 정의를 한 줄로 적고 선지를 다시 판단",
    coachingTemplate: "{topic}에서 개념 정의가 흔들립니다. 이번 주는 정의를 먼저 고정한 뒤 기출을 풉니다.",
    isUserVisible: true,
  },
  {
    tagId: "legal_effect_unclear",
    group: "concept_gap",
    internalName: "Legal effect unclear",
    userLabel: "법률효과 불안정",
    summaryLabel: "개념 공백",
    reviewPriorityWeight: 50,
    reviewAction: "요건 판단 뒤 법률효과를 따로 표시",
    coachingTemplate: "{topic}에서 법률효과 연결이 약합니다. 효과를 먼저 말로 고정하고 문제를 풉니다.",
    isUserVisible: true,
  },
  {
    tagId: "condition_missing",
    group: "condition_logic_failure",
    internalName: "Condition missing",
    userLabel: "요건 누락",
    summaryLabel: "요건 판단 실패",
    reviewPriorityWeight: 85,
    reviewAction: "요건 체크리스트를 먼저 적고 선지 판단",
    coachingTemplate: "{topic}에서 필요한 요건을 빠뜨리는 패턴이 보입니다. 요건 체크리스트 방식으로 훈련합니다.",
    isUserVisible: true,
  },
  {
    tagId: "condition_combination_failure",
    group: "condition_logic_failure",
    internalName: "Condition combination failure",
    userLabel: "요건 결합 실패",
    summaryLabel: "요건 판단 실패",
    reviewPriorityWeight: 90,
    reviewAction: "여러 요건을 함께 묶어 판단",
    coachingTemplate: "{topic}에서 요건 결합 실패가 반복됩니다. 요건을 하나씩 외우기보다 함께 묶어 판단합니다.",
    isUserVisible: true,
  },
  {
    tagId: "exception_clause_missed",
    group: "exception_missed",
    internalName: "Exception clause missed",
    userLabel: "예외 조문 누락",
    summaryLabel: "예외 누락",
    reviewPriorityWeight: 85,
    reviewAction: "원칙과 예외를 분리해서 다시 읽기",
    coachingTemplate: "{topic}에서 예외와 단서 조항을 놓칩니다. 원칙/예외를 분리 표시하며 복습합니다.",
    isUserVisible: true,
  },
  {
    tagId: "scope_limit_missed",
    group: "exception_missed",
    internalName: "Scope limit missed",
    userLabel: "적용 범위 제한 누락",
    summaryLabel: "예외 누락",
    reviewPriorityWeight: 80,
    reviewAction: "당사자/제3자/등기 전후 적용 범위를 표시",
    coachingTemplate: "{topic}에서 적용 범위 제한을 놓칩니다. 선지마다 적용 대상을 표시합니다.",
    isUserVisible: true,
  },
  {
    tagId: "similar_rule_confusion",
    group: "similar_concept_confusion",
    internalName: "Similar rule confusion",
    userLabel: "유사 개념 혼동",
    summaryLabel: "유사 개념 혼동",
    reviewPriorityWeight: 80,
    reviewAction: "두 개념의 차이표를 보고 선지 비교",
    coachingTemplate: "{topic}에서 유사 개념 비교형 문항이 흔들립니다. 쌍으로 묶어 차이를 정리합니다.",
    isUserVisible: true,
  },
  {
    tagId: "mistake_fraud_confusion",
    group: "similar_concept_confusion",
    internalName: "Mistake and fraud confusion",
    userLabel: "착오·사기 혼동",
    summaryLabel: "유사 개념 혼동",
    reviewPriorityWeight: 80,
    reviewAction: "착오와 사기의 요건 차이를 비교",
    coachingTemplate: "의사표시에서 착오·사기 판단 기준이 섞입니다. 비교형 선지를 우선 훈련합니다.",
    isUserVisible: true,
  },
  {
    tagId: "void_cancel_confusion",
    group: "similar_concept_confusion",
    internalName: "Void and cancellation confusion",
    userLabel: "무효·취소 혼동",
    summaryLabel: "유사 개념 혼동",
    reviewPriorityWeight: 80,
    reviewAction: "무효와 취소의 효과, 주장자, 추인 가능성 비교",
    coachingTemplate: "무효와 취소의 효과가 섞입니다. 효과와 주장자를 나누어 복습합니다.",
    isUserVisible: true,
  },
  {
    tagId: "agency_type_confusion",
    group: "similar_concept_confusion",
    internalName: "Agency type confusion",
    userLabel: "대리 유형 혼동",
    summaryLabel: "유사 개념 혼동",
    reviewPriorityWeight: 80,
    reviewAction: "표현대리/무권대리/대리권 남용을 비교",
    coachingTemplate: "대리 파트에서 유형 구분이 흔들립니다. 표현대리와 무권대리를 비교 훈련합니다.",
    isUserVisible: true,
  },
  {
    tagId: "choice_comparison_failure",
    group: "choice_judgment_error",
    internalName: "Choice comparison failure",
    userLabel: "선지 비교 실패",
    summaryLabel: "선지 판단 오류",
    reviewPriorityWeight: 60,
    reviewAction: "선지의 절대어, 범위어, 부정 표현 표시",
    coachingTemplate: "{topic}에서 비슷한 선지 비교가 흔들립니다. 표현 표시 후 비교하는 방식으로 풉니다.",
    isUserVisible: true,
  },
  {
    tagId: "fact_pattern_mapping_error",
    group: "case_application_failure",
    internalName: "Fact pattern mapping error",
    userLabel: "사례 적용 실패",
    summaryLabel: "사례 적용 실패",
    reviewPriorityWeight: 75,
    reviewAction: "사실관계와 요건을 나란히 대응 표시",
    coachingTemplate: "{topic}에서 사실관계를 요건에 연결하는 연습이 필요합니다.",
    isUserVisible: true,
  },
  {
    tagId: "article_requirement_gap",
    group: "article_memory_gap",
    internalName: "Article requirement gap",
    userLabel: "조문 요건 기억 불안정",
    summaryLabel: "조문 기억 불안정",
    reviewPriorityWeight: 65,
    reviewAction: "조문상 요건을 빠짐없이 체크",
    coachingTemplate: "{topic}에서 조문 요건 기억이 흔들립니다. 요건 암기와 적용을 함께 확인합니다.",
    isUserVisible: true,
  },
  {
    tagId: "low_confidence_correct",
    group: "confidence_issue",
    internalName: "Low confidence correct",
    userLabel: "확신 낮은 정답",
    summaryLabel: "확신 낮은 정답",
    reviewPriorityWeight: 35,
    reviewAction: "정답 근거를 한 줄로 복기",
    coachingTemplate: "{topic}에서 맞혔지만 확신이 낮은 문항이 쌓입니다. 맞힌 문제도 근거 확인 리뷰에 포함합니다.",
    isUserVisible: true,
  },
  {
    tagId: "time_pressure_guess",
    group: "time_pressure_guess",
    internalName: "Time pressure guess",
    userLabel: "시간 부족 추측",
    summaryLabel: "시간 압박",
    reviewPriorityWeight: 30,
    reviewAction: "기준 시간을 넘긴 지점과 판단 근거 확인",
    coachingTemplate: "{topic}에서 시간이 길어지면 추측 선택이 발생합니다. 기준 시간 안에서 판단 순서를 고정합니다.",
    isUserVisible: true,
  },
];

export function getCivilLawRootCauseTag(tagId: RootCauseTagId) {
  return CIVIL_LAW_ROOT_CAUSE_TAGS.find((tag) => tag.tagId === tagId) ?? CIVIL_LAW_ROOT_CAUSE_TAGS[0];
}
