import type { FormulaFamilyDefinition } from "@/lib/actuary-first/types";

export const probabilityFormulaFamilies: Record<string, FormulaFamilyDefinition> = {
  basic_probability_ratio: {
    formula_family_id: "basic_probability_ratio",
    public_label: "기본 확률 비율",
    internal_description: "favorable_count / total_count",
    linked_problem_family: "basic_probability",
    expected_inputs: ["favorable_count", "total_count"],
    expected_output_form: "fraction",
    accepted_equivalent_forms: ["a/b", "reduced_fraction", "decimal_equivalent"],
    variable_schema_id: "count_ratio_basic_v1",
    verifier_mode: "exact_or_rational",
    representative_failure_class: "final_answer_mismatch",
    review_enabled: true,
  },
  conditional_probability_basic: {
    formula_family_id: "conditional_probability_basic",
    public_label: "조건부확률",
    internal_description: "P(A∩B) / P(B)",
    linked_problem_family: "conditional_probability",
    expected_inputs: ["P_A_intersect_B", "P_B"],
    expected_output_form: "fraction",
    accepted_equivalent_forms: ["P(A∩B)/P(B)", "ratio_decimal_equivalent"],
    variable_schema_id: "conditional_probability_direction_v1",
    verifier_mode: "symbolic_ratio",
    representative_failure_class: "variable_misuse",
    review_enabled: true,
  },
  bayes_rule_basic: {
    formula_family_id: "bayes_rule_basic",
    public_label: "베이즈 정리",
    internal_description: "P(B|A)P(A) / P(B)",
    linked_problem_family: "bayes_rule",
    expected_inputs: ["P_B_given_A", "P_A", "P_B"],
    expected_output_form: "fraction",
    accepted_equivalent_forms: ["P(B|A)P(A)/P(B)", "posterior_fraction"],
    variable_schema_id: "bayes_binary_event_v1",
    verifier_mode: "symbolic_expression",
    representative_failure_class: "formula_selection_error",
    review_enabled: true,
  },
  expectation_discrete_basic: {
    formula_family_id: "expectation_discrete_basic",
    public_label: "이산형 기대값",
    internal_description: "ΣxP(X=x)",
    linked_problem_family: "expectation",
    expected_inputs: ["value_prob_pairs"],
    expected_output_form: "numeric",
    accepted_equivalent_forms: ["sigma_sum", "expanded_sum"],
    variable_schema_id: "discrete_value_probability_pairs_v1",
    verifier_mode: "symbolic_sum",
    representative_failure_class: "arithmetic_slip",
    review_enabled: true,
  },
  variance_discrete_basic: {
    formula_family_id: "variance_discrete_basic",
    public_label: "이산형 분산",
    internal_description: "E[X^2] - (E[X])^2 or Σ(x-μ)^2p",
    linked_problem_family: "variance",
    expected_inputs: ["value_prob_pairs", "optional_E_X"],
    expected_output_form: "numeric",
    accepted_equivalent_forms: ["EX2_minus_square_mean", "centered_second_moment"],
    variable_schema_id: "variance_discrete_v1",
    verifier_mode: "symbolic_expression",
    representative_failure_class: "formula_selection_error",
    review_enabled: true,
  },
  permutation_combination_probability: {
    formula_family_id: "permutation_combination_probability",
    public_label: "조합/순열 확률",
    internal_description: "count using nCr or nPr before ratio",
    linked_problem_family: "combinatorics_probability",
    expected_inputs: ["n", "r", "favorable_expression", "total_expression"],
    expected_output_form: "fraction",
    accepted_equivalent_forms: ["nCr", "nPr", "factorial_expanded"],
    variable_schema_id: "combinatorics_count_v1",
    verifier_mode: "symbolic_combinatoric",
    representative_failure_class: "formula_selection_error",
    review_enabled: true,
  },
  binomial_basic: {
    formula_family_id: "binomial_basic",
    public_label: "이항분포 기초",
    internal_description: "nCk p^k (1-p)^(n-k)",
    linked_problem_family: "discrete_distribution_basic",
    expected_inputs: ["n", "k", "p"],
    expected_output_form: "numeric",
    accepted_equivalent_forms: ["canonical_binomial", "factor_order_equivalent"],
    variable_schema_id: "binomial_parameters_v1",
    verifier_mode: "symbolic_distribution",
    representative_failure_class: "formula_selection_error",
    review_enabled: true,
  },
  poisson_basic: {
    formula_family_id: "poisson_basic",
    public_label: "포아송분포 기초",
    internal_description: "e^-lambda * lambda^k / k!",
    linked_problem_family: "discrete_distribution_basic",
    expected_inputs: ["lambda", "k"],
    expected_output_form: "numeric",
    accepted_equivalent_forms: ["canonical_poisson", "factor_order_equivalent"],
    variable_schema_id: "poisson_parameters_v1",
    verifier_mode: "symbolic_distribution",
    representative_failure_class: "formula_selection_error",
    review_enabled: true,
  },
};

