import type { ProbabilitySet } from "@/lib/actuary-first/types";

export const probabilitySampleSet: ProbabilitySet = {
  id: "intro-12",
  examId: "actuary_first",
  subjectId: "probability",
  title: "확률론 Starter 12",
  sourceLabel: "샘플 probability set",
  timeLimitMinutes: 24,
  questions: [
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-1",
      question_number: 1,
      problem_family: "basic_probability",
      unit_id: "probability.basic_ratio",
      difficulty: "low",
      expected_time_seconds: 70,
      stem: "8장의 카드 중 빨간 카드가 3장일 때, 한 장을 임의로 뽑아 빨간 카드일 확률은?",
      choices: [
        { id: "1", text: "3/8", value: "3/8" },
        { id: "2", text: "5/8", value: "5/8" },
        { id: "3", text: "3/5", value: "3/5" },
        { id: "4", text: "8/3", value: "8/3" },
        { id: "5", text: "1/8", value: "1/8" },
      ],
      correct_choice_id: "1",
      correct_answer_value: "3/8",
      answer_format: "fraction",
      formula_family_id: "basic_probability_ratio",
      accepted_formula_family_ids: ["basic_probability_ratio"],
      variable_schema_id: "count_ratio_basic_v1",
      tolerance_abs: 0,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: false,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "basic_ratio_setup",
          label: "유리한 경우와 전체 경우 비율",
          expectedPatterns: ["3/8"],
        },
      ],
      formula_options: [
        { value: "basic_probability_ratio", label: "유리한 경우 / 전체 경우" },
        { value: "conditional_probability_basic", label: "조건부확률" },
        { value: "permutation_combination_probability", label: "조합/순열 확률" },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-2",
      question_number: 2,
      problem_family: "conditional_probability",
      unit_id: "probability.conditional",
      difficulty: "medium",
      expected_time_seconds: 95,
      stem: "P(A∩B)=0.18, P(B)=0.3 일 때 P(A|B)는?",
      choices: [
        { id: "1", text: "0.06", value: 0.06 },
        { id: "2", text: "0.48", value: 0.48 },
        { id: "3", text: "0.6", value: 0.6 },
        { id: "4", text: "1.67", value: 1.67 },
        { id: "5", text: "0.9", value: 0.9 },
      ],
      correct_choice_id: "3",
      correct_answer_value: 0.6,
      answer_format: "numeric",
      formula_family_id: "conditional_probability_basic",
      accepted_formula_family_ids: ["conditional_probability_basic"],
      variable_schema_id: "conditional_probability_direction_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: true,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "ratio_setup",
          label: "비율식 한 줄",
          expectedPatterns: ["P(A∩B)", "/P(B)", "0.18/0.3"],
        },
      ],
      formula_options: [
        { value: "conditional_probability_basic", label: "P(A∩B)/P(B)" },
        { value: "bayes_rule_basic", label: "베이즈 정리" },
        { value: "basic_probability_ratio", label: "기본 확률 비율" },
      ],
      variable_binding_prompts: [
        {
          field: "conditioningEvent",
          label: "조건으로 두는 사건",
          options: [
            { value: "A", label: "A" },
            { value: "B", label: "B" },
          ],
        },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-3",
      question_number: 3,
      problem_family: "bayes_rule",
      unit_id: "probability.bayes",
      difficulty: "medium",
      expected_time_seconds: 110,
      stem: "P(A)=0.2, P(B|A)=0.8, P(B)=0.4 일 때 P(A|B)는?",
      choices: [
        { id: "1", text: "0.2", value: 0.2 },
        { id: "2", text: "0.4", value: 0.4 },
        { id: "3", text: "0.5", value: 0.5 },
        { id: "4", text: "0.8", value: 0.8 },
        { id: "5", text: "1.0", value: 1.0 },
      ],
      correct_choice_id: "2",
      correct_answer_value: 0.4,
      answer_format: "numeric",
      formula_family_id: "bayes_rule_basic",
      accepted_formula_family_ids: ["bayes_rule_basic"],
      variable_schema_id: "bayes_binary_event_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: true,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "bayes_setup",
          label: "베이즈 분자/분모 세팅",
          expectedPatterns: ["P(B|A)P(A)", "/P(B)", "0.8*0.2"],
        },
      ],
      formula_options: [
        { value: "bayes_rule_basic", label: "P(B|A)P(A)/P(B)" },
        { value: "conditional_probability_basic", label: "P(A∩B)/P(B)" },
        { value: "basic_probability_ratio", label: "기본 확률 비율" },
      ],
      variable_binding_prompts: [
        {
          field: "posterior",
          label: "구하려는 값",
          options: [
            { value: "P(A|B)", label: "P(A|B)" },
            { value: "P(B|A)", label: "P(B|A)" },
          ],
        },
        {
          field: "likelihood",
          label: "likelihood로 쓰는 항",
          options: [
            { value: "P(B|A)", label: "P(B|A)" },
            { value: "P(A|B)", label: "P(A|B)" },
          ],
        },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-4",
      question_number: 4,
      problem_family: "expectation",
      unit_id: "probability.expectation",
      difficulty: "medium",
      expected_time_seconds: 100,
      stem: "X가 0,1,2를 각각 0.2,0.5,0.3의 확률로 가질 때 E[X]는?",
      choices: [
        { id: "1", text: "0.8", value: 0.8 },
        { id: "2", text: "1.1", value: 1.1 },
        { id: "3", text: "1.3", value: 1.3 },
        { id: "4", text: "1.5", value: 1.5 },
        { id: "5", text: "1.8", value: 1.8 },
      ],
      correct_choice_id: "2",
      correct_answer_value: 1.1,
      answer_format: "numeric",
      formula_family_id: "expectation_discrete_basic",
      accepted_formula_family_ids: ["expectation_discrete_basic"],
      variable_schema_id: "discrete_value_probability_pairs_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: false,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "expectation_sum",
          label: "기대값 합 전개",
          expectedPatterns: ["0*0.2", "1*0.5", "2*0.3", "Σ"],
        },
      ],
      formula_options: [
        { value: "expectation_discrete_basic", label: "ΣxP(X=x)" },
        { value: "variance_discrete_basic", label: "E[X²]-(E[X])²" },
        { value: "basic_probability_ratio", label: "유리한 경우 / 전체 경우" },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-5",
      question_number: 5,
      problem_family: "variance",
      unit_id: "probability.variance",
      difficulty: "high",
      expected_time_seconds: 120,
      stem: "X가 0,1,2를 각각 0.2,0.5,0.3의 확률로 가질 때 Var(X)는?",
      choices: [
        { id: "1", text: "0.29", value: 0.29 },
        { id: "2", text: "0.41", value: 0.41 },
        { id: "3", text: "0.49", value: 0.49 },
        { id: "4", text: "0.69", value: 0.69 },
        { id: "5", text: "1.21", value: 1.21 },
      ],
      correct_choice_id: "2",
      correct_answer_value: 0.41,
      answer_format: "numeric",
      formula_family_id: "variance_discrete_basic",
      accepted_formula_family_ids: ["variance_discrete_basic"],
      variable_schema_id: "variance_discrete_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: false,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "variance_setup",
          label: "분산 핵심 전개",
          expectedPatterns: ["E[X^2]", "(E[X])^2", "Σ"],
        },
      ],
      formula_options: [
        { value: "variance_discrete_basic", label: "E[X²]-(E[X])²" },
        { value: "expectation_discrete_basic", label: "ΣxP(X=x)" },
        { value: "binomial_basic", label: "이항분포 PMF" },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-6",
      question_number: 6,
      problem_family: "combinatorics_probability",
      unit_id: "probability.combinatorics",
      difficulty: "medium",
      expected_time_seconds: 110,
      stem: "5명 중 2명을 순서 없이 뽑을 때 특정 두 사람이 함께 뽑힐 확률은?",
      choices: [
        { id: "1", text: "1/10", value: "1/10" },
        { id: "2", text: "1/5", value: "1/5" },
        { id: "3", text: "2/5", value: "2/5" },
        { id: "4", text: "2/10", value: "2/10" },
        { id: "5", text: "4/5", value: "4/5" },
      ],
      correct_choice_id: "1",
      correct_answer_value: "1/10",
      answer_format: "fraction",
      formula_family_id: "permutation_combination_probability",
      accepted_formula_family_ids: ["permutation_combination_probability"],
      variable_schema_id: "combinatorics_count_v1",
      tolerance_abs: 0,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: true,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "combinatorics_setup",
          label: "조합식 세팅",
          expectedPatterns: ["5C2", "1/10", "favorable"],
        },
      ],
      formula_options: [
        { value: "permutation_combination_probability", label: "조합/순열 확률" },
        { value: "basic_probability_ratio", label: "유리한 경우 / 전체 경우" },
        { value: "binomial_basic", label: "이항분포" },
      ],
      variable_binding_prompts: [
        {
          field: "nRole",
          label: "n이 의미하는 값",
          options: [
            { value: "total", label: "전체 사람 수" },
            { value: "selected", label: "뽑는 사람 수" },
          ],
        },
        {
          field: "rRole",
          label: "r이 의미하는 값",
          options: [
            { value: "selected", label: "뽑는 사람 수" },
            { value: "total", label: "전체 사람 수" },
          ],
        },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-7",
      question_number: 7,
      problem_family: "discrete_distribution_basic",
      unit_id: "probability.distribution.binomial",
      difficulty: "medium",
      expected_time_seconds: 105,
      stem: "X~Bin(3,0.5)일 때 P(X=2)는?",
      choices: [
        { id: "1", text: "1/8", value: 0.125 },
        { id: "2", text: "3/8", value: 0.375 },
        { id: "3", text: "1/2", value: 0.5 },
        { id: "4", text: "5/8", value: 0.625 },
        { id: "5", text: "3/4", value: 0.75 },
      ],
      correct_choice_id: "2",
      correct_answer_value: 0.375,
      answer_format: "numeric",
      formula_family_id: "binomial_basic",
      accepted_formula_family_ids: ["binomial_basic"],
      variable_schema_id: "binomial_parameters_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: true,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "binomial_setup",
          label: "이항분포 PMF 세팅",
          expectedPatterns: ["3C2", "0.5^2", "(1-0.5)"],
        },
      ],
      formula_options: [
        { value: "binomial_basic", label: "nCk p^k (1-p)^(n-k)" },
        { value: "poisson_basic", label: "e^-λ λ^k / k!" },
        { value: "expectation_discrete_basic", label: "ΣxP(X=x)" },
      ],
      variable_binding_prompts: [
        {
          field: "nRole",
          label: "n의 의미",
          options: [
            { value: "trial_count", label: "시행 횟수" },
            { value: "success_count", label: "성공 횟수" },
          ],
        },
        {
          field: "kRole",
          label: "k의 의미",
          options: [
            { value: "success_count", label: "성공 횟수" },
            { value: "trial_count", label: "시행 횟수" },
          ],
        },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-8",
      question_number: 8,
      problem_family: "discrete_distribution_basic",
      unit_id: "probability.distribution.poisson",
      difficulty: "medium",
      expected_time_seconds: 105,
      stem: "X~Poisson(2)일 때 P(X=0)는?",
      choices: [
        { id: "1", text: "e^-2", value: 0.1353352832 },
        { id: "2", text: "2e^-2", value: 0.2706705664 },
        { id: "3", text: "1- e^-2", value: 0.8646647168 },
        { id: "4", text: "1/2", value: 0.5 },
        { id: "5", text: "2", value: 2 },
      ],
      correct_choice_id: "1",
      correct_answer_value: 0.1353352832,
      answer_format: "numeric",
      formula_family_id: "poisson_basic",
      accepted_formula_family_ids: ["poisson_basic"],
      variable_schema_id: "poisson_parameters_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: true,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "poisson_setup",
          label: "포아송 PMF 세팅",
          expectedPatterns: ["e^-2", "2^0", "/0!"],
        },
      ],
      formula_options: [
        { value: "poisson_basic", label: "e^-λ λ^k / k!" },
        { value: "binomial_basic", label: "이항분포 PMF" },
        { value: "basic_probability_ratio", label: "유리한 경우 / 전체 경우" },
      ],
      variable_binding_prompts: [
        {
          field: "lambdaRole",
          label: "lambda의 의미",
          options: [
            { value: "rate", label: "평균 발생 횟수" },
            { value: "count", label: "실제 사건 횟수" },
          ],
        },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-9",
      question_number: 9,
      problem_family: "conditional_probability",
      unit_id: "probability.conditional",
      difficulty: "medium",
      expected_time_seconds: 95,
      stem: "P(A∩B)=0.12, P(A)=0.4 일 때 P(B|A)는?",
      choices: [
        { id: "1", text: "0.3", value: 0.3 },
        { id: "2", text: "0.48", value: 0.48 },
        { id: "3", text: "0.52", value: 0.52 },
        { id: "4", text: "0.7", value: 0.7 },
        { id: "5", text: "0.12", value: 0.12 },
      ],
      correct_choice_id: "1",
      correct_answer_value: 0.3,
      answer_format: "numeric",
      formula_family_id: "conditional_probability_basic",
      accepted_formula_family_ids: ["conditional_probability_basic"],
      variable_schema_id: "conditional_probability_direction_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: true,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "conditional_setup_2",
          label: "조건부확률 한 줄",
          expectedPatterns: ["P(A∩B)", "/P(A)", "0.12/0.4"],
        },
      ],
      formula_options: [
        { value: "conditional_probability_basic", label: "P(A∩B)/P(A)" },
        { value: "bayes_rule_basic", label: "베이즈 정리" },
        { value: "basic_probability_ratio", label: "기본 확률 비율" },
      ],
      variable_binding_prompts: [
        {
          field: "conditioningEvent",
          label: "조건으로 두는 사건",
          options: [
            { value: "A", label: "A" },
            { value: "B", label: "B" },
          ],
        },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-10",
      question_number: 10,
      problem_family: "expectation",
      unit_id: "probability.expectation",
      difficulty: "low",
      expected_time_seconds: 90,
      stem: "X가 1,2,3을 각각 0.2,0.3,0.5의 확률로 가질 때 E[X]는?",
      choices: [
        { id: "1", text: "1.8", value: 1.8 },
        { id: "2", text: "2.1", value: 2.1 },
        { id: "3", text: "2.3", value: 2.3 },
        { id: "4", text: "2.5", value: 2.5 },
        { id: "5", text: "3.0", value: 3.0 },
      ],
      correct_choice_id: "3",
      correct_answer_value: 2.3,
      answer_format: "numeric",
      formula_family_id: "expectation_discrete_basic",
      accepted_formula_family_ids: ["expectation_discrete_basic"],
      variable_schema_id: "discrete_value_probability_pairs_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: false,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "expectation_sum_2",
          label: "기대값 합 전개",
          expectedPatterns: ["1*0.2", "2*0.3", "3*0.5", "Σ"],
        },
      ],
      formula_options: [
        { value: "expectation_discrete_basic", label: "ΣxP(X=x)" },
        { value: "variance_discrete_basic", label: "분산 공식" },
        { value: "basic_probability_ratio", label: "유리한 경우 / 전체 경우" },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-11",
      question_number: 11,
      problem_family: "variance",
      unit_id: "probability.variance",
      difficulty: "medium",
      expected_time_seconds: 105,
      stem: "Var(X)=E[X^2]-(E[X])^2 를 사용하는 문제군은?",
      choices: [
        { id: "1", text: "기본 확률 비율", value: "basic_probability_ratio" },
        { id: "2", text: "조건부확률", value: "conditional_probability_basic" },
        { id: "3", text: "기대값", value: "expectation_discrete_basic" },
        { id: "4", text: "분산", value: "variance_discrete_basic" },
        { id: "5", text: "포아송분포", value: "poisson_basic" },
      ],
      correct_choice_id: "4",
      correct_answer_value: "variance_discrete_basic",
      answer_format: "choice_only",
      formula_family_id: "variance_discrete_basic",
      accepted_formula_family_ids: ["variance_discrete_basic"],
      variable_schema_id: "variance_discrete_v1",
      tolerance_abs: 0,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_formula",
      requires_intermediate_work: false,
      requires_variable_binding: false,
      requires_formula_selection_check: true,
      supports_intermediate_steps: false,
      step_check_mode: "none",
      formula_options: [
        { value: "variance_discrete_basic", label: "Var(X)=E[X^2]-(E[X])^2" },
        { value: "expectation_discrete_basic", label: "E[X]=ΣxP(X=x)" },
        { value: "binomial_basic", label: "nCk p^k (1-p)^(n-k)" },
      ],
    },
    {
      exam_id: "actuary_first",
      subject_id: "probability",
      set_id: "intro-12",
      question_id: "prob-12",
      question_number: 12,
      problem_family: "combinatorics_probability",
      unit_id: "probability.combinatorics",
      difficulty: "medium",
      expected_time_seconds: 100,
      stem: "서로 다른 4권 중 2권을 고르는 경우의 수는?",
      choices: [
        { id: "1", text: "4", value: 4 },
        { id: "2", text: "6", value: 6 },
        { id: "3", text: "8", value: 8 },
        { id: "4", text: "12", value: 12 },
        { id: "5", text: "16", value: 16 },
      ],
      correct_choice_id: "2",
      correct_answer_value: 6,
      answer_format: "numeric",
      formula_family_id: "permutation_combination_probability",
      accepted_formula_family_ids: ["permutation_combination_probability"],
      variable_schema_id: "combinatorics_count_v1",
      tolerance_abs: 0.000001,
      tolerance_rel: 0.000001,
      expected_input_form: "choice_plus_work",
      requires_intermediate_work: true,
      requires_variable_binding: true,
      requires_formula_selection_check: true,
      supports_intermediate_steps: true,
      step_check_mode: "key_steps",
      key_step_prompts: [
        {
          id: "combination_setup_2",
          label: "조합 한 줄",
          expectedPatterns: ["4C2", "6"],
        },
      ],
      formula_options: [
        { value: "permutation_combination_probability", label: "조합 4C2" },
        { value: "basic_probability_ratio", label: "유리한 경우 / 전체 경우" },
        { value: "binomial_basic", label: "이항분포" },
      ],
      variable_binding_prompts: [
        {
          field: "nRole",
          label: "n의 의미",
          options: [
            { value: "total", label: "전체 권수" },
            { value: "selected", label: "고르는 권수" },
          ],
        },
        {
          field: "rRole",
          label: "r의 의미",
          options: [
            { value: "selected", label: "고르는 권수" },
            { value: "total", label: "전체 권수" },
          ],
        },
      ],
    },
  ],
};

export function getProbabilitySampleSet(setId: string) {
  if (setId === probabilitySampleSet.id) {
    return probabilitySampleSet;
  }

  return {
    ...probabilitySampleSet,
    id: setId,
    questions: probabilitySampleSet.questions.map((question) => ({
      ...question,
      set_id: setId,
    })),
  };
}
