import type { ProblemFamily, ProblemFamilyStepRulePack } from "@/lib/actuary-first/types";

export const probabilityStepRulePacks: Record<ProblemFamily, ProblemFamilyStepRulePack> = {
  basic_probability: {
    problem_family: "basic_probability",
    required: false,
    strictness: "loose",
    expected_key_step_patterns: [["favorable", "total"], ["/"]],
    missing_failure_class: "verification_missing",
    partial_match_failure_class: "step_omission",
    weak_formula_failure_class: "weak_formula_evidence",
    review_message_seed: "유리한 경우와 전체 경우를 먼저 나눠 적어 보세요.",
    coaching_theme_seed: "기본 확률 비율 정리",
  },
  conditional_probability: {
    problem_family: "conditional_probability",
    required: true,
    strictness: "moderate",
    expected_key_step_patterns: [["P(", "∩", ")"], ["/P("]],
    missing_failure_class: "verification_missing",
    partial_match_failure_class: "step_omission",
    weak_formula_failure_class: "weak_formula_evidence",
    review_message_seed: "분모 사건을 먼저 분리해 적어 보세요.",
    coaching_theme_seed: "조건부확률 분모 사건 분리",
  },
  bayes_rule: {
    problem_family: "bayes_rule",
    required: true,
    strictness: "strict",
    expected_key_step_patterns: [["P(B|A)", "P(A)"], ["/P(B)"]],
    missing_failure_class: "verification_missing",
    partial_match_failure_class: "step_omission",
    weak_formula_failure_class: "weak_formula_evidence",
    review_message_seed: "사후확률과 likelihood 방향을 먼저 나눠 적어 보세요.",
    coaching_theme_seed: "베이즈 방향 분리",
  },
  expectation: {
    problem_family: "expectation",
    required: true,
    strictness: "moderate",
    expected_key_step_patterns: [["*", "0."], ["Σ"]],
    missing_failure_class: "verification_missing",
    partial_match_failure_class: "step_omission",
    weak_formula_failure_class: "weak_formula_evidence",
    review_message_seed: "값과 확률을 한 줄씩 짝지어 적어 보세요.",
    coaching_theme_seed: "기댓값 합 구조 정리",
  },
  variance: {
    problem_family: "variance",
    required: true,
    strictness: "strict",
    expected_key_step_patterns: [["E[X^2]"], ["(E[X])^2"]],
    missing_failure_class: "verification_missing",
    partial_match_failure_class: "step_omission",
    weak_formula_failure_class: "weak_formula_evidence",
    review_message_seed: "분산 식을 먼저 하나로 고정하고 계산을 시작해 보세요.",
    coaching_theme_seed: "분산 공식 고정",
  },
  combinatorics_probability: {
    problem_family: "combinatorics_probability",
    required: true,
    strictness: "moderate",
    expected_key_step_patterns: [["C", "favorable"], ["total", "/"]],
    missing_failure_class: "verification_missing",
    partial_match_failure_class: "step_omission",
    weak_formula_failure_class: "weak_formula_evidence",
    review_message_seed: "favorable count와 total count를 먼저 분리해 적어 보세요.",
    coaching_theme_seed: "조합 count 분리",
  },
  discrete_distribution_basic: {
    problem_family: "discrete_distribution_basic",
    required: true,
    strictness: "moderate",
    expected_key_step_patterns: [["=", "/", "^"]],
    missing_failure_class: "verification_missing",
    partial_match_failure_class: "step_omission",
    weak_formula_failure_class: "weak_formula_evidence",
    review_message_seed: "분포 PMF 형태를 먼저 한 줄로 적어 보세요.",
    coaching_theme_seed: "분포 PMF 먼저 적기",
  },
};

export function getProbabilityStepRulePack(problemFamily: ProblemFamily) {
  return probabilityStepRulePacks[problemFamily];
}
