import type { VariableSchemaDefinition } from "@/lib/actuary-first/types";

export const probabilityVariableSchemas: Record<string, VariableSchemaDefinition> = {
  count_ratio_basic_v1: {
    variable_schema_id: "count_ratio_basic_v1",
    linked_formula_family_id: "basic_probability_ratio",
    variables: [
      {
        variable_name: "favorable_count",
        role: "분자 count",
        expected_type: "integer",
        required: true,
        allowed_aliases: ["favorable", "success_count"],
        constraints: [">=0", "<=total_count"],
        common_misuse_patterns: ["total_count와 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "total_count",
        role: "분모 count",
        expected_type: "integer",
        required: true,
        allowed_aliases: ["total", "sample_space_count"],
        constraints: [">0"],
        common_misuse_patterns: ["favorable_count와 교체"],
        verifier_check_required: true,
      },
    ],
  },
  conditional_probability_direction_v1: {
    variable_schema_id: "conditional_probability_direction_v1",
    linked_formula_family_id: "conditional_probability_basic",
    variables: [
      {
        variable_name: "P_A_intersect_B",
        role: "결합사건 확률",
        expected_type: "probability",
        required: true,
        allowed_aliases: ["P_AB", "P_A_and_B"],
        constraints: ["0<=x<=1"],
        common_misuse_patterns: ["P(A|B)와 혼동"],
        verifier_check_required: true,
      },
      {
        variable_name: "P_B",
        role: "조건 사건 확률",
        expected_type: "probability",
        required: true,
        allowed_aliases: ["prob_B"],
        constraints: ["0<x<=1"],
        common_misuse_patterns: ["P_A와 교체"],
        verifier_check_required: true,
      },
    ],
  },
  bayes_binary_event_v1: {
    variable_schema_id: "bayes_binary_event_v1",
    linked_formula_family_id: "bayes_rule_basic",
    variables: [
      {
        variable_name: "P_B_given_A",
        role: "likelihood",
        expected_type: "probability",
        required: true,
        allowed_aliases: ["likelihood"],
        constraints: ["0<=x<=1"],
        common_misuse_patterns: ["P_A_given_B와 방향 혼동"],
        verifier_check_required: true,
      },
      {
        variable_name: "P_A",
        role: "prior",
        expected_type: "probability",
        required: true,
        allowed_aliases: ["prior_A"],
        constraints: ["0<=x<=1"],
        common_misuse_patterns: ["P_B와 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "P_B",
        role: "evidence",
        expected_type: "probability",
        required: true,
        allowed_aliases: ["evidence_B"],
        constraints: ["0<x<=1"],
        common_misuse_patterns: ["P_A_given_B와 교체"],
        verifier_check_required: true,
      },
    ],
  },
  discrete_value_probability_pairs_v1: {
    variable_schema_id: "discrete_value_probability_pairs_v1",
    linked_formula_family_id: "expectation_discrete_basic",
    variables: [
      {
        variable_name: "x_i",
        role: "이산값",
        expected_type: "number",
        required: true,
        allowed_aliases: ["x", "value"],
        constraints: ["finite"],
        common_misuse_patterns: ["p_i와 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "p_i",
        role: "각 값의 확률",
        expected_type: "probability",
        required: true,
        allowed_aliases: ["prob_i", "weight_i"],
        constraints: ["0<=x<=1", "sum=1"],
        common_misuse_patterns: ["x_i와 교체"],
        verifier_check_required: true,
      },
    ],
  },
  variance_discrete_v1: {
    variable_schema_id: "variance_discrete_v1",
    linked_formula_family_id: "variance_discrete_basic",
    variables: [
      {
        variable_name: "x_i",
        role: "이산값",
        expected_type: "number",
        required: true,
        allowed_aliases: ["x", "value"],
        constraints: ["finite"],
        common_misuse_patterns: ["p_i와 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "p_i",
        role: "확률",
        expected_type: "probability",
        required: true,
        allowed_aliases: ["prob_i"],
        constraints: ["0<=x<=1", "sum=1"],
        common_misuse_patterns: ["x_i와 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "E_X",
        role: "기대값 결과",
        expected_type: "number",
        required: false,
        allowed_aliases: ["mu", "mean"],
        constraints: ["derived_only"],
        common_misuse_patterns: ["Var_X와 교체"],
        verifier_check_required: true,
      },
    ],
  },
  combinatorics_count_v1: {
    variable_schema_id: "combinatorics_count_v1",
    linked_formula_family_id: "permutation_combination_probability",
    variables: [
      {
        variable_name: "n",
        role: "전체 개수",
        expected_type: "integer",
        required: true,
        allowed_aliases: ["N", "total_items"],
        constraints: [">=0"],
        common_misuse_patterns: ["r와 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "r",
        role: "선택 개수",
        expected_type: "integer",
        required: true,
        allowed_aliases: ["k", "select_count"],
        constraints: ["0<=r<=n"],
        common_misuse_patterns: ["n과 교체"],
        verifier_check_required: true,
      },
    ],
  },
  binomial_parameters_v1: {
    variable_schema_id: "binomial_parameters_v1",
    linked_formula_family_id: "binomial_basic",
    variables: [
      {
        variable_name: "n",
        role: "시행 횟수",
        expected_type: "integer",
        required: true,
        allowed_aliases: ["trial_count"],
        constraints: ["n>=0"],
        common_misuse_patterns: ["k와 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "k",
        role: "성공 횟수",
        expected_type: "integer",
        required: true,
        allowed_aliases: ["success_count"],
        constraints: ["0<=k<=n"],
        common_misuse_patterns: ["n과 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "p",
        role: "성공 확률",
        expected_type: "probability",
        required: true,
        allowed_aliases: ["prob_success"],
        constraints: ["0<=p<=1"],
        common_misuse_patterns: ["q와 교체"],
        verifier_check_required: true,
      },
    ],
  },
  poisson_parameters_v1: {
    variable_schema_id: "poisson_parameters_v1",
    linked_formula_family_id: "poisson_basic",
    variables: [
      {
        variable_name: "lambda",
        role: "강도 파라미터",
        expected_type: "positive_number",
        required: true,
        allowed_aliases: ["λ", "rate"],
        constraints: [">0"],
        common_misuse_patterns: ["k와 교체"],
        verifier_check_required: true,
      },
      {
        variable_name: "k",
        role: "사건 횟수",
        expected_type: "integer",
        required: true,
        allowed_aliases: ["count"],
        constraints: ["k>=0"],
        common_misuse_patterns: ["lambda와 교체"],
        verifier_check_required: true,
      },
    ],
  },
};

