import assert from "node:assert/strict";
import test from "node:test";
import { parseQuestionReference } from "../lib/review-os/first-stage/kernel/domain.ts";
import { createSubjectAdapterRegistry, validateAttemptEvaluation } from "../lib/review-os/first-stage/subject-adapter/subject-adapter.ts";
import { createOwnerOriginalApplication, authorizeOwnerOriginalAdapter, authorizeOwnerOriginalCatalog, activeOwnerOriginalCatalog, activeOwnerOriginalReference, ownerOriginalBankCandidates } from "../lib/review-os/first-stage/runtime/owner-original-context.ts";
import { OWNER_ORIGINAL_ADAPTER, OWNER_ORIGINAL_IDS, OWNER_ORIGINAL_PACKET_SHA256, OWNER_ORIGINAL_VERSION } from "../lib/review-os/first-stage/runtime/owner-original-boundary.ts";
import { loadOwnerOriginalContent } from "../lib/review-os/first-stage/runtime/owner-original-content.ts";
import { createPrivateFirstStageSessionService, privateSessionDigest as digest } from "../lib/review-os/first-stage/runtime/session-service.ts";
import { selectQfI1BankFirstAssignmentV1 as select } from "../lib/question-foundry/runtime/qf-i1-bank-first.ts";
// Unit-only synthetic adapter. Private approved bodies are never committed.
const env={NODE_ENV:"development",NEXT_PUBLIC_SUPABASE_URL:"http://127.0.0.1:55431",INVERGE_OWNER_ORIGINAL_TEST_ONLY:"isolated_synthetic",INVERGE_OWNER_ORIGINAL_REAL_ESTATE_ENABLED:"true",INVERGE_OWNER_FIRST_STAGE_KERNEL_ENABLED:"true",ALPHA_ADMIN_EMAILS:"synthetic@example.test",INVERGE_OWNER_FIRST_STAGE_EMAILS:"synthetic@example.test"};
const auth={isAuthenticated:true,isDemo:false,source:"supabase",userId:"synthetic-owner",email:"synthetic@example.test"};
const reference=(i=0)=>parseQuestionReference({schemaVersion:"first_stage.owner_original_question_reference.v1",questionId:OWNER_ORIGINAL_IDS[i],questionVersion:OWNER_ORIGINAL_VERSION,subjectId:"real_estate_principles",examYear:null,examRound:null,questionNumber:null,sessionId:"owner-original-real-estate-v2",choiceCount:5,sourceVersionManifestIds:[`owner-original-${OWNER_ORIGINAL_PACKET_SHA256}`],rightsState:"owner_authorized_original",currentnessState:"stated_model_only"});
const evidence=kind=>({schemaVersion:"first_stage.immutable_evidence_reference.v1",evidenceId:kind,evidenceVersion:"synthetic-v1",evidenceSha256:digest(kind)});
const concept={schemaVersion:"first_stage.concept_binding.v1",conceptId:"synthetic-concept",conceptVersion:"v1",subjectId:"real_estate_principles",role:"primary"};
function catalog(){
 const a={schemaVersion:"dabangil.first_stage.subject_adapter.v1",adapterId:OWNER_ORIGINAL_ADAPTER,adapterVersion:"1",subjectId:"real_estate_principles",assertQuestionReference(r){assert.ok(activeOwnerOriginalReference(a,r));},
 presentQuestion(r){this.assertQuestionReference(r);return {schemaVersion:"first_stage.mcq_question_presentation.v1",questionReference:r,stem:"Synthetic unit fixture",choices:[1,2,3,4,5].map(choiceId=>({choiceId,body:`Synthetic ${choiceId}`})),sourceStatusLabel:r.rightsState,currentnessStatusLabel:r.currentnessState,learningReferenceDisclaimer:true};},
 evaluateSubmission(input){const r=input.questionReference;return validateAttemptEvaluation(a,input,{schemaVersion:"first_stage.attempt_evaluation.v1",decision:input.submission.selectedChoice===2?"correct":"incorrect",errorCause:null,conceptBindings:[concept],biggestGapCode:"selection_comparison",nextActionCode:"practice",retryDisposition:"retry_now",reviewAfterMs:0,evaluationPolicyVersion:"synthetic-v1",evidenceEnvelope:{schemaVersion:"first_stage.attempt_evidence_envelope.v1",attemptId:input.attempt.attemptId,submissionSha256:input.submissionSha256,questionId:r.questionId,questionVersion:r.questionVersion,questionReferenceSha256:digest(r),subjectId:r.subjectId,adapterId:a.adapterId,adapterVersion:a.adapterVersion,officialKeyReference:null,calculationKeyReference:evidence("calculation"),choiceSetReference:evidence("choices"),sourceReference:evidence("source"),versionDecisionReference:evidence("version"),rightsDecisionReference:evidence("rights"),reviewedFeedback:{schemaVersion:"first_stage.owner_original_calculation_feedback.v1",state:"machine_checked_owner_local",receiptReference:null,reviewerIdentity:null,reviewerClass:null,modelAlone:true}}});},
 buildIndependentRetry(){return {schemaVersion:"first_stage.independent_retry_candidate.v1",questionReference:reference(1),lineageReceipt:{schemaVersion:"first_stage.independent_retry_lineage_receipt.v1",receiptId:"synthetic-retry-receipt",receiptVersion:"synthetic-v1",adapterId:a.adapterId,adapterVersion:a.adapterVersion,subjectId:a.subjectId,sourceQuestionId:reference().questionId,sourceQuestionVersion:reference().questionVersion,sourceQuestionReferenceSha256:digest(reference()),variantQuestionId:reference(1).questionId,variantQuestionVersion:reference(1).questionVersion,variantQuestionReferenceSha256:digest(reference(1)),targetConceptBindingKeys:[`${concept.subjectId}:${concept.conceptId}@${concept.conceptVersion}:${concept.role}`],priorRetryCount:0,decision:"unreviewed_owner_local_practice_retry"}};}};
 authorizeOwnerOriginalAdapter(a);
 const c={digest:digest("synthetic-authorized-unit"),registry:createSubjectAdapterRegistry([a]),initialReferences:[reference()],retryAvailability:(r,used)=>used.length?"exhausted":"available",explanation:()=>({text:"Synthetic reference after durable answer",sourceStatus:"machine_checked_owner_local",learningReferenceDisclaimer:true})};
 authorizeOwnerOriginalCatalog(c,[{candidateId:OWNER_ORIGINAL_IDS[0],candidateDigest:`sha256:${digest(reference())}`,familyId:"synthetic-family",surfaceId:OWNER_ORIGINAL_IDS[0],bankClass:"LEARNING_PRACTICE",origin:"BANK_STOCK",contentAuthority:"LEARNING_ONLY",rightsStatus:"OWNER_AUTHORIZED_ORIGINAL",sourceStatus:"STATED_MODEL_ONLY",releaseChainComplete:false,unseenEligibilitySnapshotSealed:false,nonSameSurfaceAsSource:false,familyIsolated:false,calibrationState:"UNASSESSED",timedProtocolBound:false,chronology:null,chronologyAuthority:null,availableAt:"2026-09-17T00:00:00.000Z",priority:0}]);return c;
}
async function scoped(run,overrides={}){let error,entered=false;const app=createOwnerOriginalApplication({environment:()=>env,session:async()=>auth,repository:()=>{throw Error("unit only");},catalog:async()=>{entered=true;try{await run();}catch(e){error=e;}return null;},...overrides});const response=await app(new Request("http://127.0.0.1:3884/api/unit"));if(error)throw error;return {response,entered};}
const request=candidates=>({purpose:"LEARNING_PRACTICE",learnerScopeId:auth.userId,sourceCandidateId:"source",sourceFamilyId:"source",sourceSurfaceId:"source",asOf:"2026-09-17T12:00:00.000Z",candidates,exposures:[]});
test("authored capability requires exact reference, genuine Owner, local environment and live object",async()=>{let saved,candidates;await scoped(()=>{saved=catalog();const a=saved.registry.require("real_estate_principles");for(const delta of [{examYear:2025},{questionNumber:96},{questionId:"unapproved"},{sourceVersionManifestIds:["wrong"]},{subjectId:"economics_principles"}]){assert.equal(activeOwnerOriginalReference(a,{...reference(),...delta}),false);assert.throws(()=>parseQuestionReference({...reference(),...delta}));}candidates=ownerOriginalBankCandidates(saved);assert.equal(select(request(candidates)).status,"ASSIGNED");assert.throws(()=>select(request([{...candidates[0]}])));assert.equal(activeOwnerOriginalReference({...a},reference()),false);});assert.equal(activeOwnerOriginalCatalog(saved),false);assert.throws(()=>select(request(candidates)));for(const overrides of [{environment:()=>({...env,VERCEL_ENV:"preview"})},{environment:()=>({...env,NEXT_PUBLIC_SUPABASE_URL:"https://remote.invalid"})},{session:async()=>({...auth,isAuthenticated:false})},{session:async()=>({...auth,email:"other@example.test"})},{session:async()=>({...auth,isDemo:true})}]){const result=await scoped(()=>assert.fail("must deny"),overrides);assert.equal(result.entered,false);assert.equal(result.response.status,404);}assert.equal(await loadOwnerOriginalContent(async()=>Buffer.from("not exact approved bytes")),null);});
const submit=(attemptId,revision,id,choice=1)=>({action:"submit",requestId:id,expectedRevision:revision,attemptId,submission:{selectedChoice:choice,confidence:"medium",answerChanged:false,previousChoice:null,eliminatedChoiceIds:[],workTrace:{schemaVersion:"first_stage.work_trace.v1",steps:[{sequence:1,kind:"select_answer",atElapsedMs:0,choiceId:choice}]}}});
test("authored exposure survives durable replay and retry; functional testing never becomes independent evidence",async()=>{await scoped(async()=>{const c=catalog(),rows=new Map();const store={async load(owner,id){return structuredClone(rows.get(id)??null);},async listOwnerSnapshot(){return {sessions:structuredClone([...rows.values()]),complete:true};},async create(v){if(!rows.has(v.sessionId))rows.set(v.sessionId,structuredClone(v));return structuredClone(rows.get(v.sessionId));},async replace(v,rev){if(rows.get(v.sessionId).state.revision!==rev)return false;rows.set(v.sessionId,structuredClone(v));return true;}};
 const service=createPrivateFirstStageSessionService(store,c,()=>"2026-09-17T12:00:00.000Z");
 for(const use of ["answer_seen","functional_test","practice"]){const created=await service.create(auth.userId,{requestId:`create-${use}`,questionId:reference().questionId});const id=created.sessionId;const begin={action:"begin",requestId:`begin-${use}`,expectedRevision:1,questionId:reference().questionId,ownerOriginalUse:use};await assert.rejects(()=>service.execute(auth.userId,id,{...begin,ownerOriginalUse:"unknown"}));const started=await service.execute(auth.userId,id,begin);assert.equal(started.state.attempts[0].assistanceLevel,use==="practice"?"none":"answer_revealed");assert.equal((await service.view(auth.userId,id)).explanation,null);const command=submit(started.state.attempts[0].attemptId,2,`submit-${use}`);const saved=await service.execute(auth.userId,id,command);assert.deepEqual(await service.execute(auth.userId,id,command),saved);const reopened=createPrivateFirstStageSessionService(store,c,()=>"2026-09-17T12:00:00.000Z");assert.equal((await reopened.view(auth.userId,id)).submittedResponse.ownerOriginalUse,use);const retry={action:"retry",requestId:`retry-${use}`,expectedRevision:3,reviewTaskId:saved.state.reviewTasks[0].reviewTaskId,ownerOriginalUse:use};if(use==="functional_test")await assert.rejects(()=>reopened.execute(auth.userId,id,{...retry,ownerOriginalUse:"practice"}));const begun=await reopened.execute(auth.userId,id,retry);const finished=await reopened.execute(auth.userId,id,submit(begun.state.attempts.at(-1).attemptId,4,`finish-${use}`,2));assert.equal(finished.state.reviewTasks[0].status,"completed");assert.equal(finished.state.conceptStates[0].state,"practice_retry_recorded");assert.equal(finished.state.conceptStates[0].masteryClaim,false);assert.equal(finished.state.independentRetries[0].lineageReceipt.decision,"unreviewed_owner_local_practice_retry");assert.equal(reopened.projectHistory(finished,auth.userId).committedAttempts[1].independentEvidence,false);}
 });});
