import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,readFile,readdir} from "node:fs/promises";
import os from "node:os";import path from "node:path";
import {THEORY_POLICY as policy,initializeTheoryBudget,testOwnerTheoryConnection,authorizeTheoryDevelopment,readTheoryDevelopmentApproval,reserveTheoryDevelopmentCall,reserveTheoryCall,readTheoryBudget,generateOwnerTheory} from "../lib/owner-study/owner-pc-theory-budget.mjs";
const user="cccccccc-cccc-4ccc-8ccc-cccccccccccc";
async function fixture(){const root=path.join(await mkdtemp(path.join(os.tmpdir(),"theory-dev-")),"budget");const settings={version:policy.version,model:policy.model,ownerId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",projectId:"synthetic-project",apiKey:"synthetic-not-a-provider-key",paidProjectVerified:true,dataSharingEnabled:false,verifiedAt:new Date().toISOString(),verificationEvidenceSha256:"a".repeat(64)};await initializeTheoryBudget(root,settings);await testOwnerTheoryConnection(root,settings,async()=>Response.json({modelVersion:policy.model,candidates:[{finishReason:"STOP",content:{parts:[{text:"READY"}]}}]}));await authorizeTheoryDevelopment(root,settings,{userId:user,questionSha256:"b".repeat(64),supabaseUrl:"http://127.0.0.1:55431"});const development=await readTheoryDevelopmentApproval(root,settings);return {root,settings,authority:{userId:user,sourceItemId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",purpose:"app1_initial_analysis",questionSha256:"b".repeat(64),development}};}
test("development shares existing spend without consuming or replacing personal case",async()=>{const f=await fixture();const before=await readFile(path.join(f.root,"installation.json"),"utf8");await reserveTheoryDevelopmentCall(f.root,f.settings,f.authority);const b=await readTheoryBudget(f.root,f.settings);assert.equal(b.usedReservations,2);assert.equal(b.caseId,null);assert.equal(b.remainingMicros,policy.budgetMicros-2*policy.reservationMicros);assert.equal(await readFile(path.join(f.root,"installation.json"),"utf8"),before);await reserveTheoryCall(f.root,f.settings,{userId:f.settings.ownerId,sourceItemId:"dddddddd-dddd-4ddd-8ddd-dddddddddddd",purpose:"app1_initial_analysis"});assert.equal((await readTheoryBudget(f.root,f.settings)).usedReservations,3);assert.equal((await readTheoryBudget(f.root,f.settings)).caseId,"dddddddd-dddd-4ddd-8ddd-dddddddddddd");await assert.rejects(authorizeTheoryDevelopment(f.root,f.settings,{userId:user,questionSha256:"b".repeat(64),supabaseUrl:"http://127.0.0.1:55431"}),{code:"EEXIST"});});
test("six concurrent development reservations are permanent across restart and same global cap",async()=>{const f=await fixture();const out=await Promise.allSettled(Array.from({length:12},()=>reserveTheoryDevelopmentCall(f.root,f.settings,f.authority)));assert.equal(out.filter(x=>x.status==="fulfilled").length,6);assert.ok(out.filter(x=>x.status==="rejected").every(x=>x.reason.code==="OWNER_THEORY_DEVELOPMENT_CALL_LIMIT"));assert.equal((await readTheoryBudget(f.root,f.settings)).usedReservations,7);await assert.rejects(reserveTheoryDevelopmentCall(f.root,f.settings,f.authority),{code:"OWNER_THEORY_DEVELOPMENT_CALL_LIMIT"});});
test("development binds exact question, isolated account and local DB, at most three source items",async()=>{const f=await fixture();for(const delta of [{userId:f.settings.ownerId},{questionSha256:"c".repeat(64)},{development:{...f.authority.development,supabaseUrl:"http://127.0.0.1:55421"}}])await assert.rejects(reserveTheoryDevelopmentCall(f.root,f.settings,{...f.authority,...delta}),{code:"OWNER_THEORY_DEVELOPMENT_BINDING_MISMATCH"});for(const n of [1,2,3])await reserveTheoryDevelopmentCall(f.root,f.settings,{...f.authority,sourceItemId:`dddddddd-dddd-4ddd-8ddd-${String(n).padStart(12,"0")}`});await assert.rejects(reserveTheoryDevelopmentCall(f.root,f.settings,f.authority),{code:"OWNER_THEORY_DEVELOPMENT_SOURCE_LIMIT"});assert.equal((await readTheoryBudget(f.root,f.settings)).usedReservations,4);});
test("unknown development transport is charged and cannot be refunded by retry",async()=>{const f=await fixture();const req={contents:[{role:"user",parts:[{text:"SYNTHETIC_PRIVATE_BODY"}]}],generationConfig:{temperature:0.1}};await assert.rejects(generateOwnerTheory(f.root,f.settings,f.authority,req,async()=>{throw Error("unknown timeout");}));assert.equal((await readTheoryBudget(f.root,f.settings)).usedReservations,2);const result=JSON.parse(await readFile(path.join(f.root,"result-02.json"),"utf8"));assert.equal(result.status,"unknown");assert.equal(result.estimatedCostMicros,null);for(const name of await readdir(f.root))assert.ok(!(await readFile(path.join(f.root,name),"utf8")).includes("SYNTHETIC_PRIVATE_BODY"));});
