import type { RootCauseTagDefinition, RootCauseTagId } from "@/lib/appraisal-first/types";

export const LEGAL_REGULATIONS_ROOT_CAUSE_TAGS: RootCauseTagDefinition[] = [
  {
    tagId: "statute_article_recall_gap",
    group: "article_memory_gap",
    internalName: "Statute article recall gap",
    userLabel: "Article recall gap",
    summaryLabel: "Article recall",
    reviewPriorityWeight: 70,
    reviewAction: "Review the statute basis first, then re-judge the same option set.",
    coachingTemplate: "{topic} is showing weak article recall. Lock the statute basis before retrying related questions.",
    isUserVisible: true,
  },
  {
    tagId: "deadline_requirement_gap",
    group: "article_memory_gap",
    internalName: "Deadline requirement gap",
    userLabel: "Deadline recall gap",
    summaryLabel: "Deadline recall",
    reviewPriorityWeight: 75,
    reviewAction: "Write the procedure steps with each deadline before reviewing options.",
    coachingTemplate: "{topic} is mixing procedure timing and deadlines. Start with a deadline table, then retry questions.",
    isUserVisible: true,
  },
  {
    tagId: "authority_subject_confusion",
    group: "condition_logic_failure",
    internalName: "Authority subject confusion",
    userLabel: "Authority confusion",
    summaryLabel: "Authority subject",
    reviewPriorityWeight: 82,
    reviewAction: "Mark the institution, authority holder, and required action in each option.",
    coachingTemplate: "{topic} is showing authority-subject confusion. Compare who acts, who decides, and who receives notice.",
    isUserVisible: true,
  },
  {
    tagId: "procedure_order_confusion",
    group: "condition_logic_failure",
    internalName: "Procedure order confusion",
    userLabel: "Procedure order confusion",
    summaryLabel: "Procedure order",
    reviewPriorityWeight: 86,
    reviewAction: "Draw the procedure order first, then attach actor and deadline to each step.",
    coachingTemplate: "{topic} is showing procedure-order mistakes. Rebuild the sequence before doing another set.",
    isUserVisible: true,
  },
  {
    tagId: "statute_scope_missed",
    group: "exception_missed",
    internalName: "Statute scope missed",
    userLabel: "Scope limit missed",
    summaryLabel: "Scope limit",
    reviewPriorityWeight: 80,
    reviewAction: "Separate the applicable target, excluded target, and exception phrase.",
    coachingTemplate: "{topic} is showing scope-limit misses. Split target, exclusion, and exception before retrying.",
    isUserVisible: true,
  },
  {
    tagId: "similar_statute_confusion",
    group: "similar_concept_confusion",
    internalName: "Similar statute confusion",
    userLabel: "Similar statute confusion",
    summaryLabel: "Similar statute",
    reviewPriorityWeight: 78,
    reviewAction: "Compare the similar statute units by actor, procedure, and legal effect.",
    coachingTemplate: "{topic} is showing similar-statute confusion. Compare nearby institutions side by side.",
    isUserVisible: true,
  },
  {
    tagId: "sanction_effect_confusion",
    group: "concept_gap",
    internalName: "Sanction effect confusion",
    userLabel: "Sanction effect confusion",
    summaryLabel: "Sanction effect",
    reviewPriorityWeight: 72,
    reviewAction: "Separate cancellation, suspension, duty, and penalty effects.",
    coachingTemplate: "{topic} needs clearer sanction-effect separation. Review each legal effect as a distinct row.",
    isUserVisible: true,
  },
  {
    tagId: "choice_comparison_failure",
    group: "choice_judgment_error",
    internalName: "Choice comparison failure",
    userLabel: "Option comparison failure",
    summaryLabel: "Option judgment",
    reviewPriorityWeight: 60,
    reviewAction: "Underline authority, deadline, exception, and effect words in each option.",
    coachingTemplate: "{topic} is showing option-comparison mistakes. Compare options by authority, deadline, and exception words.",
    isUserVisible: true,
  },
  {
    tagId: "exception_clause_missed",
    group: "exception_missed",
    internalName: "Exception clause missed",
    userLabel: "Exception clause missed",
    summaryLabel: "Exception missed",
    reviewPriorityWeight: 84,
    reviewAction: "Review the general rule and exception as separate statements.",
    coachingTemplate: "{topic} is showing missed exception clauses. Review the general rule and exception separately.",
    isUserVisible: true,
  },
  {
    tagId: "condition_combination_failure",
    group: "condition_logic_failure",
    internalName: "Condition combination failure",
    userLabel: "Condition combination failure",
    summaryLabel: "Condition logic",
    reviewPriorityWeight: 84,
    reviewAction: "Convert the legal requirement into a checklist before judging options.",
    coachingTemplate: "{topic} is showing requirement-combination mistakes. Use a checklist before option judgment.",
    isUserVisible: true,
  },
  {
    tagId: "low_confidence_correct",
    group: "confidence_issue",
    internalName: "Low confidence correct",
    userLabel: "Low-confidence correct",
    summaryLabel: "Low confidence",
    reviewPriorityWeight: 35,
    reviewAction: "Re-state the statute basis for the correct option.",
    coachingTemplate: "{topic} was correct but weakly grounded. Confirm the statute basis for correctly answered items.",
    isUserVisible: true,
  },
  {
    tagId: "time_pressure_guess",
    group: "time_pressure_guess",
    internalName: "Time pressure guess",
    userLabel: "Time-pressure guess",
    summaryLabel: "Time pressure",
    reviewPriorityWeight: 30,
    reviewAction: "Check whether the delay came from statute recall or option comparison.",
    coachingTemplate: "{topic} is showing slow judgment. Fix the decision order before adding more questions.",
    isUserVisible: true,
  },
];

export function getLegalRegulationsRootCauseTag(tagId: RootCauseTagId) {
  return LEGAL_REGULATIONS_ROOT_CAUSE_TAGS.find((tag) => tag.tagId === tagId) ?? LEGAL_REGULATIONS_ROOT_CAUSE_TAGS[0];
}
