import { exactObject, requiredIdentifier, requiredSafeInteger } from "../kernel/domain";
import { privateSessionDigest as digest } from "./session-service";
import { applicabilityFailure as fail, requireSame as same, requiredHash } from "./foundation-applicability";
import { FIVE, RELEASE_OBSERVATION_FIELDS, RIGHTS } from "./foundation-release-contract";
import { rows, unique, nonempty, sourcePair, TRANSPORT_FIELDS, type ReleaseContext, type Row } from "./foundation-release-rights";
import { OFFICIAL_SUBJECTS, ORIGINAL_2026_PROFILE, ECONOMICS_R3_PROFILE, profileSession, profileQuestionNumber, type OfficialProfile } from "./foundation-official-profile";

export const OFFICIAL_ROUND = ORIGINAL_2026_PROFILE.id;
export { OFFICIAL_SUBJECTS };
export const officialSession = profileSession;
const POSITION = "session_profile_id subject_id official_question_number".split(" ");
const ANSWER_ROLE = "named_owner_authorized_human_answer_key_reviewer";

/** Reviewed observations of exact private source bytes/booklet positions. They
 * are consumed from the same server installation, never fetched or generated by
 * this validator. A boolean 'official/current' on the packet has no authority. */
export function sourceObservation(ctx: ReleaseContext, references: readonly unknown[], rights: Row, role: string, profile: OfficialProfile = ORIGINAL_2026_PROFILE) {
  const matches = references.map(ref => ctx.resolve(ref, RELEASE_OBSERVATION_FIELDS)).filter(row =>
    row.source_post_id === rights.post_id && row.source_asset_id === rights.asset_id && row.raw_artifact_sha256 === rights.sha256 && row.artifact_role === role);
  if (matches.length !== 1) fail();
  const row = matches[0]; requiredIdentifier(row.booklet_id);
  if (row.official_exam_round_id !== profile.id || (profile === ECONOMICS_R3_PROFILE && row.booklet_id !== "A")) fail();
  same(row.transport_receipt, rights.transport_receipt); same(row.content_identity_receipt, rights.content_identity_receipt);
  const positions = rows(row.ordered_position_bindings);
  const fields = [...POSITION, ...(role === "official_question" ? ["source_question_anchor", "question_body_sha256"]
    : ["final_answer_row_locator", "answer_position_1_to_5"])];
  const seen = new Set<string>(), locators = new Set<string>(), sessions: string[] = [];
  for (const value of positions) {
    const position = exactObject(value, fields);
    same(position.session_profile_id, officialSession(position.subject_id, profile));
    requiredSafeInteger(position.official_question_number, profileQuestionNumber(position.subject_id, 1, profile), profileQuestionNumber(position.subject_id, 40, profile));
    const key = digest(POSITION.map(field => position[field]));
    if (seen.has(key)) fail(); seen.add(key);
    if (!sessions.includes(String(position.session_profile_id))) sessions.push(String(position.session_profile_id));
    const locator = nonempty(role === "official_question" ? position.source_question_anchor : position.final_answer_row_locator);
    if (locators.has(locator)) fail(); locators.add(locator);
    if (role === "official_question") requiredHash(position.question_body_sha256);
    else requiredSafeInteger(position.answer_position_1_to_5, 1, 5);
  }
  same(row.session_profile_ids, sessions);
  ctx.review(row, ANSWER_ROLE, "verified_exact_official_booklet_positions", rights.reviewed_at);
  return row;
}

export function validateOfficialKey(ctx: ReleaseContext, release: Row, correctChoice: unknown, source: ReturnType<typeof sourcePair>, observations: readonly unknown[], profile: OfficialProfile = ORIGINAL_2026_PROFILE) {
  const shape = FIVE.releaseReceiptContract.verifiedOfficialKeyReceiptShape;
  const key = ctx.resolve(release.verified_official_key_receipt_reference, shape.requiredFields);
  for (const field of ["item_id", "item_version", "official_exam_round_id", "session_profile_id", "subject_id", "official_question_number", "source_question_anchor"]) same(key[field], release[field]);
  same(key.source_question_post_id, source.post.row.post_id); same(key.source_question_asset_id, source.asset.row.asset_id);
  same(key.source_question_asset_sha256, source.asset.row.sha256);
  if (key.official_exam_round_id !== profile.id) fail();
  same(key.session_profile_id, officialSession(key.subject_id, profile));
  const keySource = sourcePair(ctx, key.key_post_rights_receipt_reference, key.key_asset_rights_receipt_reference);
  same(key.qnet_post_id, keySource.post.row.post_id); same(key.qnet_asset_id, keySource.asset.row.asset_id);
  same(key.exact_asset_raw_sha256, keySource.asset.row.sha256); same(key.effective_key_rights_decision, keySource.effective);
  same(key.key_post_exact_attribution, keySource.post.attribution); same(key.key_asset_exact_attribution, keySource.asset.attribution);
  const attributions = [...new Set([keySource.post.attribution, keySource.asset.attribution])];
  same(key.ordered_unique_key_attributions, attributions); same(key.ordered_unique_key_attributions_digest, digest(attributions));
  const keyObservation = sourceObservation(ctx, observations, keySource.asset.row, "official_final_answer", profile);
  const directObservation = ctx.resolve(key.asset_content_identity_receipt_reference, RELEASE_OBSERVATION_FIELDS);
  same(directObservation, keyObservation);
  const transport = ctx.resolve(key.asset_transport_receipt_reference, TRANSPORT_FIELDS);
  const rawTransport = keySource.asset.row.transport_receipt as Row;
  for (const field of ["requested_url", "final_url", "http_status", "content_type", "retrieved_at"]) same(transport[field], rawTransport[field]);
  same(transport.raw_artifact_sha256, keySource.asset.row.sha256); same(transport.byte_count, keySource.asset.row.byte_count);
  const tableShape = shape.officialKeyTableMappingReceiptShape;
  const table = ctx.resolve(key.official_key_table_mapping_receipt_reference, tableShape.requiredFields);
  same(table.official_exam_round_id, profile.id);
  same(table.final_answer_post_id, key.qnet_post_id); same(table.final_answer_asset_id, key.qnet_asset_id);
  same(table.final_answer_asset_sha256, key.exact_asset_raw_sha256); same(table.final_answer_asset_rights_receipt_reference, key.key_asset_rights_receipt_reference);
  const tableRows = rows(table.ordered_key_rows, 200, 200);
  if (table.row_count !== 200) fail();
  same(table.ordered_key_rows_digest, digest(tableRows)); same(key.official_key_table_mapping_digest, table.ordered_key_rows_digest);
  const assetRefs = unique(table.source_question_asset_rights_receipt_references);
  const assetMap = new Map<string, { rights: Row; observation: Row }>();
  for (const ref of assetRefs) {
    const asset = ctx.resolve(ref, RIGHTS.assetRequiredFields);
    const basis = ctx.resolve(asset.primary_rights_basis_receipt_reference, RIGHTS.primaryRightsBasisReceiptShape.requiredFields);
    const observed = ctx.resolve(basis.basis_evidence_reference, RIGHTS.rightsBasisEvidenceReceiptShape.requiredFields);
    const validated = sourcePair(ctx, observed.parent_post_rights_receipt_reference_or_null, ref);
    const identity = digest([asset.post_id, asset.asset_id, asset.sha256]);
    if (assetMap.has(identity)) fail();
    const observation = sourceObservation(ctx, observations, validated.asset.row, "official_question", profile);
    same(observation.booklet_id, keyObservation.booklet_id);
    assetMap.set(identity, { rights: asset, observation });
  }
  const used = new Set<string>(), locators = new Set<string>(), anchors = new Set<string>();
  tableRows.forEach((value, index) => {
    const row = exactObject(value, tableShape.keyRowRequiredFields), subject = OFFICIAL_SUBJECTS[Math.floor(index / 40)];
    same(row.subject_id, subject); same(row.session_profile_id, officialSession(subject, profile));
    same(row.official_question_number, profileQuestionNumber(subject, index % 40 + 1, profile)); requiredSafeInteger(row.answer_position_1_to_5, 1, 5);
    const identity = digest([row.source_question_post_id, row.source_question_asset_id, row.source_question_asset_sha256]);
    const asset = assetMap.get(identity); if (!asset) fail(); used.add(identity);
    const questionMatches = rows(asset.observation.ordered_position_bindings).filter(value => POSITION.every(field => (value as Row)[field] === row[field]));
    const answerMatches = rows(keyObservation.ordered_position_bindings).filter(value => POSITION.every(field => (value as Row)[field] === row[field]));
    if (questionMatches.length !== 1 || answerMatches.length !== 1) fail();
    same((questionMatches[0] as Row).source_question_anchor, row.source_question_anchor);
    same((answerMatches[0] as Row).final_answer_row_locator, row.final_answer_row_locator);
    same((answerMatches[0] as Row).answer_position_1_to_5, row.answer_position_1_to_5);
    const anchor = digest([identity, row.source_question_anchor]), locator = nonempty(row.final_answer_row_locator);
    if (anchors.has(anchor) || locators.has(locator)) fail(); anchors.add(anchor); locators.add(locator);
  });
  if (used.size !== assetMap.size) fail();
  const matches = tableRows.filter(value => POSITION.every(field => (value as Row)[field] === key[field]));
  if (matches.length !== 1) fail();
  for (const field of tableShape.keyRowRequiredFields) same((matches[0] as Row)[field], key[field]);
  same(key.answer_position_1_to_5, correctChoice);
  ctx.review(table, ANSWER_ROLE, tableShape.requiredDecision, keySource.asset.row.reviewed_at);
  ctx.review(key, ANSWER_ROLE, shape.requiredDecision, table.reviewed_at);
  ctx.review(key, ANSWER_ROLE, shape.requiredDecision, key.retrieved_at);
  return { key, keySource, sourceObservation: sourceObservation(ctx, observations, source.asset.row, "official_question", profile) };
}
