import type { PresentValueSampleQuestion } from "@/lib/actuary-second/types";

export const presentValueSampleQuestions: PresentValueSampleQuestion[] = [
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-1",
    source_label: "pv-family-sample",
    raw_problem_text: "Discount 1,000 due in 3 years at 5% effective annual interest and state what the value represents.",
    expected_formula_family_id: "pv_single_payment_basic",
    accepted_formula_family_ids: ["pv_single_payment_basic"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric_with_conclusion",
    step_check_mode: "key_steps_plus_interpretation",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "identify_discount", label: "discount factor", expectedPatterns: ["1/(1+0.05)^3", "v^3"], required: true },
      { id: "apply_payment", label: "apply payment", expectedPatterns: ["1000"], required: true },
    ],
    interpretation_required: true,
    conclusion_required: true,
    difficulty: "medium",
    expected_time_seconds: 300,
    expected_numeric_answer: 863.84,
    interest_rate: 0.05,
    period_count: 3,
    payment_amount: 1000,
    compounding_assumption: "annual_compound",
    present_value_target: "single payment present value",
    annuity_type: "single",
    timing_convention: "end_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-2",
    source_label: "pv-family-sample",
    raw_problem_text: "At 4% effective annual interest, find the present value of 500 paid at the end of each year for 4 years.",
    expected_formula_family_id: "pv_ordinary_annuity_basic",
    accepted_formula_family_ids: ["pv_ordinary_annuity_basic", "pv_annuity_factor_form"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric",
    step_check_mode: "key_steps",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "ordinary-type", label: "ordinary annuity", expectedPatterns: ["ordinary", "end"], required: false },
      { id: "annuity-factor", label: "annuity factor", expectedPatterns: ["(1-v^4)/0.04", "a-angle-4"], required: true },
      { id: "multiply-payment", label: "multiply payment", expectedPatterns: ["500"], required: true },
    ],
    interpretation_required: false,
    conclusion_required: false,
    difficulty: "medium",
    expected_time_seconds: 360,
    expected_numeric_answer: 1814.94,
    interest_rate: 0.04,
    period_count: 4,
    payment_amount: 500,
    compounding_assumption: "annual_compound",
    present_value_target: "ordinary annuity present value",
    annuity_type: "ordinary",
    timing_convention: "end_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-3",
    source_label: "pv-family-sample",
    raw_problem_text: "At 4% effective annual interest, find the present value of 500 paid at the beginning of each year for 4 years.",
    expected_formula_family_id: "pv_annuity_due_basic",
    accepted_formula_family_ids: ["pv_annuity_due_basic", "pv_annuity_factor_form"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric",
    step_check_mode: "key_steps",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "due-type", label: "annuity due", expectedPatterns: ["due", "beginning"], required: false },
      { id: "ordinary-base", label: "ordinary base factor", expectedPatterns: ["a-angle-4", "(1-v^4)/0.04"], required: true },
      { id: "timing-adjust", label: "timing adjustment", expectedPatterns: ["(1+0.04)", "/v"], required: true },
    ],
    interpretation_required: false,
    conclusion_required: false,
    difficulty: "medium",
    expected_time_seconds: 360,
    expected_numeric_answer: 1887.54,
    interest_rate: 0.04,
    period_count: 4,
    payment_amount: 500,
    compounding_assumption: "annual_compound",
    present_value_target: "annuity due present value",
    annuity_type: "due",
    timing_convention: "beginning_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-4",
    source_label: "pv-family-sample",
    raw_problem_text: "At 3% effective annual interest, an annuity of 300 is paid for 3 years after a 1-year deferment. Find the present value.",
    expected_formula_family_id: "pv_deferred_annuity_basic",
    accepted_formula_family_ids: ["pv_deferred_annuity_basic", "pv_annuity_factor_form"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric",
    step_check_mode: "key_steps",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "deferred-factor", label: "annuity factor", expectedPatterns: ["a-angle-3", "(1-v^3)/0.03"], required: true },
      { id: "deferral", label: "deferral adjustment", expectedPatterns: ["v^1", "v", "defer"], required: true },
      { id: "multiply-payment", label: "payment amount", expectedPatterns: ["300"], required: true },
    ],
    interpretation_required: false,
    conclusion_required: false,
    difficulty: "high",
    expected_time_seconds: 420,
    expected_numeric_answer: 848.76,
    interest_rate: 0.03,
    period_count: 3,
    payment_amount: 300,
    compounding_assumption: "annual_compound",
    present_value_target: "deferred annuity present value",
    annuity_type: "deferred",
    timing_convention: "end_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-5",
    source_label: "pv-family-sample",
    raw_problem_text: "At 6% effective annual interest, compute the present value of 200 paid for 5 years using annuity-factor notation and explain what the value means.",
    expected_formula_family_id: "pv_annuity_factor_form",
    accepted_formula_family_ids: ["pv_annuity_factor_form", "pv_ordinary_annuity_basic"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric_with_conclusion",
    step_check_mode: "key_steps_plus_interpretation",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "factor-form", label: "factor form", expectedPatterns: ["a-angle-5", "(1-v^5)/0.06"], required: true },
      { id: "payment", label: "payment", expectedPatterns: ["200"], required: true },
    ],
    interpretation_required: true,
    conclusion_required: true,
    difficulty: "medium",
    expected_time_seconds: 420,
    expected_numeric_answer: 842.47,
    interest_rate: 0.06,
    period_count: 5,
    payment_amount: 200,
    compounding_assumption: "annual_compound",
    present_value_target: "annuity factor present value",
    annuity_type: "ordinary",
    timing_convention: "end_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-6",
    source_label: "pv-family-sample",
    raw_problem_text: "At 5% effective annual interest, find the present value of 400 paid at the end of each year for 3 years and finish with a direct answer sentence.",
    expected_formula_family_id: "pv_ordinary_annuity_basic",
    accepted_formula_family_ids: ["pv_ordinary_annuity_basic", "pv_annuity_factor_form"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric_with_conclusion",
    step_check_mode: "key_steps_plus_interpretation",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "annuity-factor", label: "annuity factor", expectedPatterns: ["a-angle-3", "(1-v^3)/0.05"], required: true },
      { id: "payment", label: "payment", expectedPatterns: ["400"], required: true },
    ],
    interpretation_required: true,
    conclusion_required: true,
    difficulty: "medium",
    expected_time_seconds: 360,
    expected_numeric_answer: 1089.3,
    interest_rate: 0.05,
    period_count: 3,
    payment_amount: 400,
    compounding_assumption: "annual_compound",
    present_value_target: "ordinary annuity present value",
    annuity_type: "ordinary",
    timing_convention: "end_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-7",
    source_label: "pv-family-calibration",
    raw_problem_text: "At 4% effective annual interest, find the present value of 600 paid at the beginning of each year for 3 years.",
    expected_formula_family_id: "pv_annuity_due_basic",
    accepted_formula_family_ids: ["pv_annuity_due_basic", "pv_annuity_factor_form"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric",
    step_check_mode: "key_steps",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "due-base", label: "ordinary annuity base", expectedPatterns: ["a-angle-3", "(1-v^3)/0.04"], required: true },
      { id: "due-adjust", label: "due adjustment", expectedPatterns: ["1.04", "(1+0.04)", "/v"], required: true },
    ],
    interpretation_required: false,
    conclusion_required: false,
    difficulty: "medium",
    expected_time_seconds: 360,
    expected_numeric_answer: 1730.49,
    interest_rate: 0.04,
    period_count: 3,
    payment_amount: 600,
    compounding_assumption: "annual_compound",
    present_value_target: "annuity due present value",
    annuity_type: "due",
    timing_convention: "beginning_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-8",
    source_label: "pv-family-calibration",
    raw_problem_text: "At 5% effective annual interest, an annuity of 250 is payable for 4 years after a 1-year deferment. Find the present value.",
    expected_formula_family_id: "pv_deferred_annuity_basic",
    accepted_formula_family_ids: ["pv_deferred_annuity_basic", "pv_annuity_factor_form"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric",
    step_check_mode: "key_steps",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "deferred-base", label: "base annuity factor", expectedPatterns: ["a-angle-4", "(1-v^4)/0.05"], required: true },
      { id: "deferred-adjust", label: "defer one year", expectedPatterns: ["v", "v^1", "defer"], required: true },
    ],
    interpretation_required: false,
    conclusion_required: false,
    difficulty: "medium",
    expected_time_seconds: 360,
    expected_numeric_answer: 840.6,
    interest_rate: 0.05,
    period_count: 4,
    payment_amount: 250,
    compounding_assumption: "annual_compound",
    present_value_target: "deferred annuity present value",
    annuity_type: "deferred",
    timing_convention: "end_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-9",
    source_label: "pv-family-calibration",
    raw_problem_text: "Discount 2,000 due in 2 years at 3% and state what the calculated value represents.",
    expected_formula_family_id: "pv_single_payment_basic",
    accepted_formula_family_ids: ["pv_single_payment_basic"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric_with_conclusion",
    step_check_mode: "key_steps_plus_interpretation",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "single-discount", label: "single payment discount", expectedPatterns: ["1/(1+0.03)^2", "v^2"], required: true },
      { id: "single-apply", label: "apply amount", expectedPatterns: ["2000"], required: true },
    ],
    interpretation_required: true,
    conclusion_required: true,
    difficulty: "medium",
    expected_time_seconds: 300,
    expected_numeric_answer: 1885.19,
    interest_rate: 0.03,
    period_count: 2,
    payment_amount: 2000,
    compounding_assumption: "annual_compound",
    present_value_target: "single payment present value",
    annuity_type: "single",
    timing_convention: "end_of_period",
  },
  {
    exam_id: "actuary_second",
    subject_id: "insurance_math",
    problem_family: "present_value_annuity_v1",
    question_id: "sample-10",
    source_label: "pv-family-calibration",
    raw_problem_text: "Using annuity-factor notation, compute the present value of 150 paid for 6 years at 2% and end with a final answer sentence.",
    expected_formula_family_id: "pv_annuity_factor_form",
    accepted_formula_family_ids: ["pv_annuity_factor_form", "pv_ordinary_annuity_basic"],
    variable_schema_id: "pv_annuity_core_v1",
    tolerance_abs: 0.05,
    tolerance_rel: 0.0001,
    expected_output_form: "numeric_with_conclusion",
    step_check_mode: "key_steps_plus_interpretation",
    partial_credit_policy_id: "pv_annuity_v1",
    expected_key_steps: [
      { id: "factor-notation", label: "factor notation", expectedPatterns: ["a-angle-6", "(1-v^6)/0.02"], required: true },
      { id: "factor-payment", label: "payment amount", expectedPatterns: ["150"], required: true },
    ],
    interpretation_required: true,
    conclusion_required: true,
    difficulty: "medium",
    expected_time_seconds: 360,
    expected_numeric_answer: 839.66,
    interest_rate: 0.02,
    period_count: 6,
    payment_amount: 150,
    compounding_assumption: "annual_compound",
    present_value_target: "annuity factor present value",
    annuity_type: "ordinary",
    timing_convention: "end_of_period",
  },
];

export function getPresentValueSampleQuestion(questionId: string) {
  const question = presentValueSampleQuestions.find((item) => item.question_id === questionId);
  if (!question) {
    throw new Error(`Unknown present value sample question: ${questionId}`);
  }
  return question;
}
